version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: salesmaster_db
    environment:
      POSTGRES_DB: salesMasterB2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salesMaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: salesmaster_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/salesMasterB2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: salesMaster
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: